=== kyjna0312/spring_parser/webapp/jsonFile/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema#",
    "$id": "http://example.com/example.json",
    "type": "object",
    "required": [
        "Entity",
        "interval",
        "Description",
        "DataFormat",
        "Transform"
    ],
    "properties": {
        "Entity": {"type": "string"},
        "interval": {"type": "string"},
        "Description": {
            "type": "object",
            "properties": {
                "common": {
                    "type": "object",
                    "properties": {
                        "thingsType":      {"type": "string"},
                        "deviceID":        {"type": "string"},
                        "productName":     {"type": "string"},
                        "ownerID":         {"type": "string"},
                        "manufacturer":    {"type": "string"},
                        "manufacturerID":  {"type": "string"},
                        "deviceVersion":   {"type": "string"},
                        "firmwareVersion": {"type": "string"},
                        "deviceImage":     {"type": "string"}
                    }
                },
                "access": {
                    "type": "object",
                    "properties": {
                        "currentLocation": {"type": "string"},
                        "actionEnable":    {"type": "string"},
                        "subPropertyOf":   {"type": "string"},
                        "superPropertyOf": {"type": "string"},
                        "connectionType":  {"type": "string"},
                        "discoverable":    {"type": "string"},
                        "targetIPv6":      {"type": "string"},
                        "targetIPv4":      {"type": "string"},
                        "targetAddr":      {"type": "string"},
                        "uuid":            {"type": "string"},
                        "hasInterface":    {"type": "string"}
                    }
                },
                "sensor": {
                    "type": "object",
                    "properties": {
                        "sensorType":     {"type": "string"},
                        "sensorSerialNo": {"type": "string"},
                        "sensitivity":    {"type": "string"}
                    }
                },
                "robot": {
                    "type": "object",
                    "properties": {
                        "robotFeature": {
                            "type":"array",
                            "minItems": 1,
                            "items":{
                                "type": "string"
                            }
                        },
                        "robotFeatureID": {
                            "type":"array",
                            "minItems": 1,
                            "items":{
                                "type": "string"
                            }
                        },
                        "robotFeatureIDparam": {
                            "type":"object",
                            "minProperties": 1,
                            "properties":{
                                "Func1": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items":{
                                        "type": "string",
                                        "enum": ["Null", "Int", "Float", "Char", "Long"]
                                    }
                                }
                            }
                        },
                        "robotFeatureReturn": {
                            "type":"object",
                            "minProperties": 1,
                            "properties":{
                                "Func1": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items":{
                                        "type": "string",
                                        "enum": ["Null", "Int", "Float", "Char", "Long"]
                                    }
                                }
                            }
                        }
                    }
                },
                "User": {
                    "type": "object",
                    "properties": {
                        "userID":     {"type": "string"},
                        "userName":   {"type": "string"},
                        "password":   {"type": "string"},
                        "authority ": {"type": "string"}
                    }
                },
                "DataInfo": {
                    "type": "object",
                    "properties": {
                        "dataFunctionName": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "string"
                            }
                        },
                        "dataFunctionID": {
                            "type": "array",
                            "minItems": 1,
                            "items": {
                                "type": "string"
                            }
                        },
                        "dataFunctionParam": {
                            "type": "object",
                            "minProperties": 1,
                            "properties": {
                                "Func1": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "type": "string",
                                        "enum": ["Null", "Int", "Float", "Char", "Long"]
                                    }
                                }
                            }
                        },
                        "dataFunctionReturn": {
                            "type": "object",
                            "minProperties": 1,
                            "properties": {
                                "Func1": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {
                                        "type": "string",
                                        "enum": ["Null", "Int", "Float", "Char", "Long"]
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "DataFormat": {
            "type": "object",
            "required": [
                "valueLength",
                "type",
                "hasType"
            ],
            "properties": {
                "valueLength" : {"type": "string"},
                "type" : {
                    "type": "string",
                    "enum": ["simpleType", "complexType"]
                },
                "hasType" : {
                    "type": "object",
                    "required": ["valueType"],
                    "properties": {
                        "length": {"type": "string"},
                        "valueType": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "required": [
                                    "description",
                                    "name",
                                    "dataType",
                                    "valueField",
                                    "valueRange"
                                ],
                                "properties": {
                                    "description": {"type": "string"},
                                    "name": {"type": "string"},
                                    "dataType": {
                                        "type": "string",
                                        "enum": ["Null", "Int", "Float", "Char", "Long"]
                                    },
                                    "valueField": {"type": "string"},
                                    "valueRange": {
                                        "type": "array",
                                        "minItems": 2,
                                        "maxItems": 2,
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "Transform": {
            "type": "object",
            "required": [
                "valueType",
                "basisValue",
                "gatherValue"
            ],
            "properties": {
                "valueType": {
                    "type": "object",
                    "properties": {
                        "collectorModel":{
                            "type": "object",
                            "properties": {
                                "Collector_ID": {"type": "string"},
                                "overrideDataFormat": {
                                    "type": "string",
                                    "enum": ["true", "false"]
                                },
                                "type": {
                                    "type": "string",
                                    "enum": ["simpleType", "complexType"]
                                },
                                "length": {"type": "string"}
                            }
                        },
                        "hasType" : {"$ref": "#/properties/DataFormat/properties/hasType"}
                    }
                },
                "basisValue": {
                    "type": "object",
                    "required": [
                        "convertingModel", 
                        "hasType"
                    ],
                    "dependencies": {
                        "lowlevelContext": ["highlevelContext"],
                        "highlevelContext": ["lowlevelContext"]
                    },
                    "properties": {
                        "convertingModel": {
                            "type": "object",
                            "properties":{
                                "converting_ID": {"type": "string"},
                                "overrideDataFormat": {"type": "string"},
                                "type": {
                                    "type": "string",
                                    "enum": ["simpleType", "complexType"]
                                },
                                "length": {"type": "string"}
                            }
                        },
                        "hasType" : {"$ref": "#/properties/DataFormat/properties/hasType"},
                        "lowlevelContext": {
                            "type": ["array", "null"],
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name":          {"type": "string"},
                                    "equation":      {"type": "string"},
                                    "targetValue":   {"type": "string"},
                                    "operator":      {"type": "string"},
                                    "resultMapping": {"type": "string"}   
                                }
                            }
                        },
                        "highlevelContext": {
                            "type": ["array", "null"], 
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {"type":"string"},
                                    "equation": {"type":"string"},
                                    "resultMapping": {
                                        "type":"object",
                                        "properties": {
                                            "trueValue": {"type": "string"},
                                            "falseValue": {"type": "string"}
                                        }
                                    },
                                    "result": {"type": "string"}
                                }
                            },
                            "result":{"type":"string"}
                        }
                    }
                },
                "gatherValue": {
                    "type": "object",
                    "dependencies": {
                        "lowlevelContext":  ["highlevelContext"],
                        "highlevelContext": ["lowlevelContext"]
                    },
                    "properties": {
                        "transformModel": {
                            "type": "object",
                            "required": [
                                "transform_ID"
                                ],
                            "properties": {
                                "transform_ID": {"type": "string"}
                            }
                        },
                        "lowlevelContext":  {"$ref": "#/properties/Transform/properties/basisValue/properties/lowlevelContext"},
                        "highlevelContext": {"$ref": "#/properties/Transform/properties/basisValue/properties/highlevelContext"}
                    }
                }
            }
        }
    }
}

=== kyjna0312/spring_parser/webapp/jsonFile/1_Robot_Alto_edit.json
{
    "Entity" : "Robot_Alto",
    "interval" : "100ms",
    "Description" : {
        "access" : {
            "currentLocation" : "TestLocation",
            "actionEnabled" : "True",
            "subPropertyOf" : "Things, Device",
            "superPropertyOf" : "RobotDevice",
            "connectionType" : "IPv4",
            "discoverable" : "True",
            "targetIPv4" : "192.168.15.100",
            "hasInterface" : "True"
        },
        "common" : {
            "deviceID" : "Yujin_Robot_Test_Alto",
            "productName" : "Yujin_Robot_Test_Alto",
            "manufacturer" : "Yujin_Robot",
            "deviceVersion" : "1.0.0",
            "firmwareVersion" : "1.0.0",
            "thingsType" : "Robot"
        },
        "robot" : {
            "robotFeature" : [
                "Echo_State",
                "Position_State"
            ],
            "robotFeatureID" : [
                "State_Robot_Alto_State",
                "State_Robot_Alto_Position"
            ],
            "robotFeatureIDparam" : {
                "Func1" : [
                    "Null"
                ],
                "Func2" : [
                    "Null"
                ]
            },
            "robotFeatureReturn" : {
                "Func1" : [
                    "Int"
                ],
                "Func2" : [
                    "Int"
                ]
            }
        }
    },
    "DataFormat" : {
        "valueLength" : "2",
        "type" : "complexType",
        "hasType" : {
            "length" : "2",
            "valueType" : [
                {
                    "description" : "State_Robot_Alto_State",
                    "name" : "Echo_State",
                    "dataType" : "Int",
                    "valueField" : "value",
                    "valueRange" : [
                        "0",
                        "10"
                    ]
                },
                {
                    "description" : "State_Robot_Alto_Position",
                    "name" : "Position_State",
                    "dataType" : "Int",
                    "valueField" : "value",
                    "valueRange" : [
                        "0",
                        "10"
                    ]
                }
            ]
        }
    },
    "Transform" : {
        "valueType" : {
            "collectorModel" : {
                "Collector_ID" : "Collector_Robot_Alto",
                "overrideDataFormat" : "false",
                "_type" : "complexType",
                "length" : "2"
            },
            "hasType" : {
                "length" : "2",
                "valueType" : [
                    {
                        "description" : "State_Robot_Alto_State",
                        "name" : "Echo_State",
                        "dataType" : "Int",
                        "valueField" : "value",
                        "valueRange" : [
                            "0",
                            "10"
                        ]
                    },
                    {
                        "description" : "State_Robot_Alto_Position",
                        "name" : "Position_State",
                        "dataType" : "Int",
                        "valueField" : "value",
                        "valueRange" : [
                            "0",
                            "10"
                        ]
                    }
                ]
            }
        },
        "basisValue" : {
            "convertingModel" : {
                "converting_ID" : "Converting_Robot_Alto",
                "overrideDataFormat" : "false",
                "_type" : "complexType",
                "length" : "2"
            },
            "hasType" : {
                "length" : "2",
                "valueType" : [
                    {
                        "description" : "State_Robot_Alto_State",
                        "name" : "Echo_State",
                        "dataType" : "Int",
                        "valueField" : "value",
                        "valueRange" : [
                            "0",
                            "10"
                        ]
                    },
                    {
                        "description" : "State_Robot_Alto_Position",
                        "name" : "Position_State",
                        "dataType" : "Int",
                        "valueField" : "value",
                        "valueRange" : [
                            "0",
                            "10"
                        ]
                    }
                ]
            },
            "lowlevelContext" : [
                {
                    "name" : "Echo_State",
                    "equation" : "value",
                    "targetValue" : "returnValue",
                    "operator" : "EqualsTo",
                    "resultMapping" : "True"
                },
                {
                    "name" : "Position_State",
                    "equation" : "value",
                    "targetValue" : "returnValue",
                    "operator" : "EqualsTo",
                    "resultMapping" : "True"
                }
            ],
            "highlevelContext" : [
                {
                    "name" : "Echo_State",
                    "equation" : "returnValue == 1",
                    "resultMapping" : {
                        "trueValue" : "State_READY",
                        "faluseValue" : "State_NOT_READY"
                    }
                },
                {
                    "name" : "Echo_State",
                    "equation" : "returnValue == 2",
                    "resultMapping" : {
                        "trueValue" : "State_MOVING"
                    }
                },
                {
                    "name" : "Echo_State",
                    "equation" : "returnValue == 3",
                    "resultMapping" : {
                        "trueValue" : "State_TOHOME"
                    }
                },
                {
                    "name" : "Poisition_State",
                    "equation" : "returnValue == 1",
                    "resultMapping" : {
                        "trueValue" : "Position_HOME"
                    }
                },
                {
                    "name" : "Poisition_State",
                    "equation" : "returnValue == 2",
                    "resultMapping" : {
                        "trueValue" : "Position_HOME"
                    }
                }
            ]
        },
        "gatherValue" : {
            "transformModel" : {
                "transform_ID" : "Transform_Robot_Alto"
            },
            "lowlevelContext" : [
                {
                    "name" : "Echo_State",
                    "equation" : "value",
                    "targetValue" : "1",
                    "operator" :"EqualsTo",
                    "resultMapping" : "State_READY"
                }
            ],
            "highlevelContext" : [
                {
                    "name" : "Echo_State",
                    "equation" : "1 == 1",
                    "resultMapping" : {
                        "trueValue" : "State_READY",
                        "faluseValue" : "State_NOT_READY"
                    },
                    "result" : "State_READY"
                }
            ]
        }
    }
}
